### ISSUE TITLE
Using with compute

### ISSUE THREAD

**Issue by craigloftus** [ROTGP/flutter_environments#1]
I quite like this pattern, but I hit a stumbling block when combining it with `compute`.

My code looks something like this:

```
import '../env.dart';

Carousel parseCarousel(Uint8List responseBytes) {
  final parsed = jsonDecode(utf8.decode(responseBytes));
  return Carousel.fromJson(parsed, Env.value.baseURL);
}

Future<Carousel> fetchCarousel(http.Client client) async {
  final response = await client.get('${Env.value.baseURL}api/carousel/');
  return compute(parseCarousel, response.bodyBytes);
}
```

The above code will compile fine, but on execution `Env.value` in `parseCarousel` will be `null` if called via `compute`.

I can 'hack' around it by passing the environment manually into `compute` as part of the message, but not being that familiar with dart I was wondering if I am missing something?

**Comment by ROTGP** [comment]
To be honest I'm still learning Dart/Flutter myself. From what I understand, `compute` runs heavy operations on a separate thread. I'm assuming that's why the reference to `Env` is lost. As you mentioned, a workaround is to pass the value in as an argument.  This app has another branch which uses the Env.of(context) pattern (inherited widget), but that would certainly fail with compute also, as the callback function passed to compute must be a global method or a static method, not a closure or an instance method.

**Comment by craigloftus** [comment]
Thanks. I think I will have stick with passing the enviroment manually to compute, or get the API fixed so I don't have to bother.

**Comment by ROTGP** [comment]
@craigloftus I asked about `compute` on stackoverflow... [here's](https://stackoverflow.com/questions/52104366/what-is-the-context-scope-of-flutters-compute-function/52104614#52104614) the answer

**Comment by craigloftus** [comment]
@ROTGP Thanks. I had come to the same conclusion.
